---

sudo: required

language: minimal

matrix:
  include:
    - dist: bionic
    - dist: focal

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

install:
  # Install ansible
  - sudo -H pip3 install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # dependencies
  - ansible-galaxy install lifeofguenter.java

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
