---

dist: bionic
language: minimal

env:
  - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

addons:
  apt:
    packages:
      - software-properties-common

before_install:
  # fix for apt/allow_downgrade
  - sudo add-apt-repository -yu ppa:deadsnakes/ppa
  - sudo apt-get -yqq install python3.10-dev

install:
  # Install ansible
  - export PATH="${PATH}:$(python3.10 -c 'import site; print(site.USER_BASE)')/bin"
  - python3.10 -m pip install --user -U pip setuptools wheel
  - python3.10 -m pip install --user -U ansible ansible-lint PyYAML

  # Check ansible versions
  - ansible --version
  - ansible-lint --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # dependencies
  - ansible-galaxy install lifeofguenter.java
  - ansible-galaxy install lifeofguenter.mongodb

script:
  - export PATH="${PATH}:$(python3.10 -c 'import site; print(site.USER_BASE)')/bin"
  - ansible-lint
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local
  - mongod --version
  - java -version
  - ls -lh /usr/lib/unifi-video/lib

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
