---

matrix:
  include:
    - dist: xenial
    - dist: bionic

language: generic
sudo: required

install:
  - python --version
  - python3 --version
  - sudo -H pip install -U pip

  # Install ansible
  - sudo -H pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # dependencies
  - ansible-galaxy install lifeofguenter.oracle-java

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local -e "ansible_python_interpreter=$(which python3)"

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local -e "ansible_python_interpreter=$(which python3)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
