---

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic

language: python
sudo: required

install:
  - pip install -U pip

  # Install ansible
  - pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # dependencies
  - ansible-galaxy install lifeofguenter.oracle-java

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
