---

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic

language: generic
sudo: required

install:
  - |
    if [ "$(lsb_release -rs)" == "14.04" ]; then
      sudo add-apt-repository -y ppa:deadsnakes/ppa
      sudo apt-get update
      sudo apt-get install -y -qq python3.6-dev
      curl https://bootstrap.pypa.io/get-pip.py -o - | sudo python3.6
      sudo ln -sf /usr/bin/python3.6 /usr/bin/python3
    fi

  - python --version
  - python3 --version
  - sudo pip install -U pip
  - sudo pip install -U urllib3 pyOpenSSL ndg-httpsclient pyasn1

  # Install ansible
  - sudo pip install -U ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

  # dependencies
  - ansible-galaxy install lifeofguenter.oracle-java

script:
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local -e "ansible_python_interpreter=$(which python3)"

  - ansible-playbook tests/test.yml -i tests/inventory --connection=local -e "ansible_python_interpreter=$(which python3)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
