---

- name: check for CVE-2021-44228
  ansible.builtin.shell:
    cmd: unzip -l log4j-core-*.jar | grep -qF org/apache/logging/log4j/core/lookup/JndiLookup.class
    chdir: /usr/lib/unifi-video/lib
  ignore_errors: true
  register: cve_check
  become: yes
  become_user: unifi-video

- name: fix CVE-2021-44228
  ansible.builtin.shell:
    cmd: zip -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class
    chdir: /usr/lib/unifi-video/lib
  when: cve_check is succeeded
  become: yes
  become_user: unifi-video
  notify:
    - stop_unifi_video
    - start_unifi_video
