---

- name: get java-home
  shell: set -eo pipefail; dirname "$(dirname "$(dpkg -L 'java-1.8.0-amazon-corretto-jdk' | grep -e bin/java$ | grep -v jre | head -n1)")"
  args:
    executable: /bin/bash
  register: unifi_video_raw_java_home
  changed_when: no
  when: unifi_video_java_home is not defined

- name: set java-home
  set_fact:
    unifi_video_java_home: "{{ unifi_video_raw_java_home.stdout }}"
  changed_when: no
  when: unifi_video_java_home is not defined

- name: fix debian
  set_fact:
    unifi_video_os_version: "{{ ansible_distribution_major_version }}"
  changed_when: no
  when:
    - ansible_distribution == 'Debian'

- name: add apt-key
  apt_key:
    url: https://d.peegeepee.com/795C6027520643F0BA02297F97B46B8582C6571E.asc
    state: present
  become: yes

- name: install prerequisites
  apt:
    name:
      - acl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: install unifi-video
  apt:
    deb: "{{ unifi_video_deb_url }}"
  become: yes

- name: add default.conf
  template:
    src: default.conf
    dest: /etc/default/unifi-video
    mode: 0644
  become: yes
  notify:
    - stop_unifi_video
    - start_unifi_video
