---

- name: get java-home
  ansible.builtin.shell: set -eo pipefail; dirname "$(dirname "$(dpkg -L 'java-1.8.0-amazon-corretto-jdk' | grep -e bin/java$ | grep -v jre | head -n1)")"
  args:
    executable: /bin/bash
  register: unifi_video_raw_java_home
  changed_when: no
  when: unifi_video_java_home is not defined

- name: set java-home
  ansible.builtin.set_fact:
    unifi_video_java_home: "{{ unifi_video_raw_java_home.stdout }}"
  changed_when: no
  when: unifi_video_java_home is not defined

- name: fix debian
  ansible.builtin.set_fact:
    unifi_video_os_version: "{{ unifi_video_os_version.split('.')[0] }}"
  changed_when: no
  when:
    - ansible_distribution == 'Debian'

- name: add apt-key
  ansible.builtin.apt_key:
    id: 795C6027520643F0BA02297F97B46B8582C6571E
    keyserver: keys.openpgp.org
    state: present
  become: yes

- name: install prerequisites
  ansible.builtin.apt:
    name:
      - acl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: install unifi-video
  ansible.builtin.apt:
    deb: "{{ unifi_video_deb_url }}"
  become: yes

- name: add default.conf
  ansible.builtin.template:
    src: default.conf
    dest: /etc/default/unifi-video
    mode: 0644
  become: yes
  notify:
    - stop_unifi_video
    - start_unifi_video
