---

- set_fact:
    unifi_video_os_version: "{{ ansible_distribution_major_version }}"
  when:
    - ansible_distribution == 'Debian'

- set_fact:
    unifi_video_os_version: 9
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'buster'

- name: add apt-key
  apt_key:
    url: https://d.peegeepee.com/795C6027520643F0BA02297F97B46B8582C6571E.asc
    state: present
  become: yes

- name: install prerequisites
  apt:
    name:
      - acl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: install unifi-video
  apt:
    deb: "{{ unifi_video_deb_url }}"

- name: add default.conf
  template:
    src: default.conf
    dest: /etc/default/unifi-video
    mode: 0644
  become: yes
  notify: restart_unifi_video
