---

- name: add apt-key
  apt_key:
    url: https://dl.ui.com/unifi/unifi-repo.gpg
    state: present
  become: yes

- name: add apt-repo
  apt_repository:
    repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present
  become: yes

- name: install unifi-video
  apt:
    name:
      - acl
      - unifi-video
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: add default.conf
  template:
    src: default.conf
    dest: /etc/default/unifi-video
    mode: 0644
  become: yes
  notify: restart_unifi_video
