---

- set_fact:
    unifi_video_repo_release: wheezy
  when: ansible_distribution_release == 'jessie'

- name: add apt-key
  apt_key:
    url: "http://www.ubnt.com/downloads/unifi-video/apt-3.x/unifi-video.gpg.key"
    state: present
  become: yes

- name: add apt-repo
  apt_repository:
    repo: deb [arch=amd64] http://www.ubnt.com/downloads/unifi-video/apt-3.x {{ unifi_video_repo_release }} ubiquiti
    state: present
  become: yes

- name: install unifi-video
  apt:
    name: unifi-video
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: add default-conf
  template:
    src: default.conf
    dest: /etc/default/unifi-video
    mode: 0644
  become: yes
