---

- name: stop_unifi_video
  ansible.builtin.systemd:
    name: unifi-video
    state: stopped
  become: yes

- name: start_unifi_video
  ansible.builtin.systemd:
    name: unifi-video
    state: started
  become: yes
